### ISSUE TITLE
NuGet Error?

### ISSUE THREAD

**Issue by d0wn2** [slowscript/warpinator-windows#1]
Hey, I just saw this project recently and think it's pretty awesome! It would be amazing to be able to easily share files between my Linux and Windows computers without uploading/downloading to a middleman.

However, when I go to compile the project in Visual Studio, it throws me the error:
```
Error		Tenhle projekt odkazuje na balíčky NuGet, které nejsou v tomhle počítači k dispozici. Když je chcete stáhnout, použijte funkci obnovení balíčků NuGet.  Další informace najdete na adrese http://go.microsoft.com/fwlink/?LinkID=322105. Chybějícím souborem je soubor packages\Grpc.Tools.2.41.0\build\Grpc.Tools.props.	Warpinator	C:\Users\user\source\repos\warpinator-windows\Warpinator\Warpinator.csproj	246
```
 
 Which when translated, becomes:
 
```
Error This project refers to NuGet packages that are not available on this computer. Use the NuGet package recovery feature to download them. Learn more at http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is packages \ Grpc.Tools.2.41.0 \ build \ Grpc.Tools.props. Warpinator C: \ Users \ user \ source \ repos \ warpinator-windows \ Warpinator \ Warpinator.csproj 246
```
 
I already followed all of the steps in that help article, and both options in Nuget are checked. Is there an issue with this project, or am I doing something wrong? Thanks!

**Comment by slowscript** [comment]
You are right, this was an issue with the project. I moved the project into its own directory which also moved where packages are stored by default and the project file didn't reflect that. Fixed in d5923bb.
