### ISSUE TITLE
Distribute this app as winget

### ISSUE THREAD

**Issue by CodeCubeNeo** [slowscript/warpinator-windows#17]

**Comment by thedoggybrad** [comment]
I have requested to have so, if it is compatible.
@CodeCubeNeo you may track its status in:
https://github.com/microsoft/winget-pkgs/issues/103088

**Comment by thedoggybrad** [comment]
I have submitted all the versions available as of writing this. Versions 0.1, 0.2 and 0.3.

**Comment by slowscript** [comment]
Seems like the installer is now available in winget. Thanks for the submission!
