### ISSUE TITLE
dont allow killing the app to stop the transfer

### ISSUE THREAD

**Issue by CodeCubeNeo** [slowscript/warpinator-windows#18]
I can click on the X button to close the app and the transfer will stop. Rather add a cancel option and if the "Run in system tray" is enabled than do not kill the transfer. Also why not merge the windows and not keep them separate?

**Comment by slowscript** [comment]
Sorry, this is a bug. The transfer should continue when the window is closed. I'll fix it (hopefully) soon.

There is no important reason to have the windows separate. It was just easier to do it this way. But at least you can see transfers with multiple remotes at the same time.

**Comment by slowscript** [comment]
Should be fixed in version 0.3
