### ISSUE TITLE
Sharing Issue on Windows App

### ISSUE THREAD

**Issue by singhravneet1998** [slowscript/warpinator-windows#22]
On Windows When I try to share anything from the right context menu by selecting the 'Send To Warpinator' option, the file transfer doesn't start unless and until I manually open the Warpinator App from the system tray, which is kind of a bummer because Warpinator is the only File Sharing Application, that has 'Automatic Accept Transfer' option which lets me transfer file without opening the app, but due to this issue, I have to manually open Warpinator from the system tray to let the transfer begin.

Please fix this issue.

**Comment by slowscript** [comment]
I've made it pop up from the tray on send-to, although you will still have to select which device should receive the files. Hopefully this is what you wanted. The fix will be part of the next update.

**Comment by slowscript** [comment]
Fix included in v0.4
