### ISSUE TITLE
start minimized doesn't work

### ISSUE THREAD

**Issue by xboxones1** [slowscript/warpinator-windows#29]
start minimized doesn't work on Windows 11, the program loads as usual, the option does not affect the behavior of the program in any way. I checked it on a virtual machine, I thought there might be something wrong with my OS, but it doesn’t work there either

**Comment by slowscript** [comment]
Do you have "Run in system tray" ticked as well? It looks like there is a bug that allows you to tick "Start minimized" even when "Run in system tray" is off. This will be fixed in the next release. With both of these checked it works fine for me.

**Comment by xboxones1** [comment]
I reset Windows settings to default and minimized worked. As for the tick, I didn’t have such a bug. Without the "Run in system tray" checkbox, cannot select "Start minimized"

**Comment by xboxones1** [comment]
I reinstalled Windows 11 and configured it, installed Warpinator and start minimized doesn't work again. It only works if you install Warpinator immediately after reinstallation. How to diagnose the problem?

**Comment by slowscript** [comment]
So I've put the `Hide()` call into `Form1_Shown` as you suggested. Does this fix your issue? Also please check that "Start minimized" is still enabled in settings. There was a bug that caused the settings to reset to default every time Warpinator was updated.

[warpinator-debug.zip](https://github.com/slowscript/warpinator-windows/files/13464629/warpinator-debug.zip)

**Comment by xboxones1** [comment]
Yes, this fixed the problem. Thank's
