### ISSUE TITLE
transfer always failed after latest update of Windows 11 Pro

### ISSUE THREAD

**Issue by michalkvasnicka** [slowscript/warpinator-windows#31]
Every trasnfer (From  Windows 11 Pro 23H2, OS Build: 22631.2715 to Linux Mint 21.2 and other Ubuntu based Linux distros) via Warpinator-windows 0.4 on Windows site failed with error: "Attempt to divide by zero".

Warpinator-windows 0.3 works well ...

Update: see attached screenshot and log file.

[latest.log](https://github.com/slowscript/warpinator-windows/files/13459247/latest.log)
![Screenshot 2023-11-24 135107](https://github.com/slowscript/warpinator-windows/assets/2698803/e994f27e-453a-4289-806e-1cc3f08e9461)

**Comment by michalkvasnicka** [comment]
any respond???

**Comment by CloneMMDDCVII** [comment]
I'm seeing a similar issue.

This seems to coincide with there being more than 1 subfolder at the root of the folder being received.

I'm sending from Warpinaotr for Android (v1.6.1)

This is what the exception text is:
```
************** Exception Text **************
System.DivideByZeroException: Attempted to divide by zero.
   at Warpinator.Transfer.<ReceiveFileChunk>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Warpinator.Remote.<StartReceiveTransfer>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
```

The log file seems useless because warpinator crashes ahead of logging anything to do with that transfer.

**Comment by michalkvasnicka** [comment]
> I'm seeing a similar issue.
I may case (Warpinator Windows 11 pro 23H2 <-> Linux Mint 21.2) transfer crash, sometimes immediately after start of transfer and sometimes few second after start of transfer. On Windows client 0.4.0 I can see open small info window with "dividing by zero" error message.

**Comment by slowscript** [comment]
So I took a blind shot at fixing this. I think the reason this happens is when the transfer of a file chunk takes less than a millisecond. I wonder how it ever worked for you, as the change from previous version was that now we use a clock with greater resolution (1 ms vs ~15 ms). I've now increased the resolution even further, which (although being unnecessary for transfer speed calculation) could prevent the divide by zero error. I am unable to reproduce the error myself, so I'd appreciate if you could confirm that this change fixed something.

[warpinator-debug.zip](https://github.com/slowscript/warpinator-windows/files/13464082/warpinator-debug.zip)

**Comment by michalkvasnicka** [comment]
Looks like, that your fix is fully functional ... :)

**Comment by slowscript** [comment]
Awesome! I've pushed the changes to GitHub and will release it as 0.4.1 (or 0.5) later. I still have some other things to fix.
