### ISSUE TITLE
Unhandled exception has occurred in your application. If you click Continue,

### ISSUE THREAD

**Issue by Miros77** [slowscript/warpinator-windows#9]
Unhandled exception has occurred in your application. If you click Continue, the application will ignore this error and attempt to continue. If you click Quit, the application will close immediately.
Failed to bind port "192. 168.0.76.42000".
![image](https://user-images.githubusercontent.com/59547044/188724474-818fec9a-b822-4b1b-8a8c-65429c080318.png)
![image](https://user-images.githubusercontent.com/59547044/188724964-30f67ae5-0b32-4481-8c3c-edf975fb830e.png)

**Crash**
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: Exceeds max packet size of 0.
   at Makaretu.Dns.MulticastService.Send(Message msg, Boolean checkDuplicate, IPEndPoint remoteEndPoint)
   at Makaretu.Dns.MulticastService.SendQuery(DomainName name, DnsClass klass, DnsType type)
   at Warpinator.Form1.RescanToolStripMenuItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4110.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
Warpinator
    Assembly Version: 0.2.0.0
    Win32 Version: 0.2.0.0
    CodeBase: file:///D:/Games/warpinator-windows_0.2/Warpinator.exe
----------------------------------------
Common.Logging.Core
    Assembly Version: 3.4.1.0
    Win32 Version: 3.4.1.0
    CodeBase: file:///D:/Games/warpinator-windows_0.2/Common.Logging.Core.DLL
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4110.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4110.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
Common.Logging
    Assembly Version: 3.4.1.0
    Win32 Version: 3.4.1.0
    CodeBase: file:///D:/Games/warpinator-windows_0.2/Common.Logging.DLL
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4110.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Makaretu.Dns
    Assembly Version: 2.0.1.0
    Win32 Version: 2.0.1
    CodeBase: file:///D:/Games/warpinator-windows_0.2/Makaretu.Dns.DLL
----------------------------------------
System.DirectoryServices.AccountManagement
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.DirectoryServices.AccountManagement/v4.0_4.0.0.0__b77a5c561934e089/System.DirectoryServices.AccountManagement.dll
----------------------------------------
Makaretu.Dns.Multicast
    Assembly Version: 0.27.0.0
    Win32 Version: 0.27.0
    CodeBase: file:///D:/Games/warpinator-windows_0.2/Makaretu.Dns.Multicast.DLL
----------------------------------------
System.DirectoryServices
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.DirectoryServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.DirectoryServices.dll
----------------------------------------
System.Net.IPNetwork
    Assembly Version: 2.1.2.0
    Win32 Version: 2.1.2.0
    CodeBase: file:///D:/Games/warpinator-windows_0.2/System.Net.IPNetwork.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
Grpc.Core.Api
    Assembly Version: 2.0.0.0
    Win32 Version: 2.41.0.0
    CodeBase: file:///D:/Games/warpinator-windows_0.2/Grpc.Core.Api.DLL
----------------------------------------
Grpc.Core
    Assembly Version: 2.0.0.0
    Win32 Version: 2.41.0.0
    CodeBase: file:///D:/Games/warpinator-windows_0.2/Grpc.Core.DLL
----------------------------------------
Google.Protobuf
    Assembly Version: 3.19.0.0
    Win32 Version: 3.19.0.0
    CodeBase: file:///D:/Games/warpinator-windows_0.2/Google.Protobuf.DLL
----------------------------------------
BouncyCastle.Crypto
    Assembly Version: 1.8.9.0
    Win32 Version: 1.8.20343.1
    CodeBase: file:///D:/Games/warpinator-windows_0.2/BouncyCastle.Crypto.DLL
----------------------------------------
System.Memory
    Assembly Version: 4.0.1.1
    Win32 Version: 4.6.28619.01
    CodeBase: file:///D:/Games/warpinator-windows_0.2/System.Memory.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by slowscript** [comment]
This exception is very strange. I'd just say that you probably shouldn't try to manually scan for devices before the application has initialized. The only useful information is this:
> Failed to bind port "192. 168.0.76.42000".
I'd need some more information when this appeared and possibly a screenshot as well. The screenshots and stack traces currently attached are unfortunately not very useful because they are a result of an uninitialized state, not the root cause why initialization did not finish correctly.

**Comment by Miros77** [comment]
I forgot to clarify, this is the first launch
